# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chirp_pb2 as chirp__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chirp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/chirp.UserService/CreateUser',
                request_serializer=chirp__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=chirp__pb2.Identifier.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/chirp.UserService/GetUser',
                request_serializer=chirp__pb2.UserRequest.SerializeToString,
                response_deserializer=chirp__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/chirp.UserService/UpdateUser',
                request_serializer=chirp__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)
        self.GetFollowing = channel.unary_unary(
                '/chirp.UserService/GetFollowing',
                request_serializer=chirp__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=chirp__pb2.Users.FromString,
                _registered_method=True)
        self.GetFollowers = channel.unary_unary(
                '/chirp.UserService/GetFollowers',
                request_serializer=chirp__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=chirp__pb2.Users.FromString,
                _registered_method=True)
        self.FollowUser = channel.unary_unary(
                '/chirp.UserService/FollowUser',
                request_serializer=chirp__pb2.UserRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)
        self.UnfollowUser = channel.unary_unary(
                '/chirp.UserService/UnfollowUser',
                request_serializer=chirp__pb2.UserRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFollowing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFollowers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FollowUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnfollowUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=chirp__pb2.CreateUserRequest.FromString,
                    response_serializer=chirp__pb2.Identifier.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=chirp__pb2.UserRequest.FromString,
                    response_serializer=chirp__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=chirp__pb2.UpdateUserRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
            'GetFollowing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFollowing,
                    request_deserializer=chirp__pb2.GetUsersRequest.FromString,
                    response_serializer=chirp__pb2.Users.SerializeToString,
            ),
            'GetFollowers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFollowers,
                    request_deserializer=chirp__pb2.GetUsersRequest.FromString,
                    response_serializer=chirp__pb2.Users.SerializeToString,
            ),
            'FollowUser': grpc.unary_unary_rpc_method_handler(
                    servicer.FollowUser,
                    request_deserializer=chirp__pb2.UserRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
            'UnfollowUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UnfollowUser,
                    request_deserializer=chirp__pb2.UserRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chirp.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chirp.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.UserService/CreateUser',
            chirp__pb2.CreateUserRequest.SerializeToString,
            chirp__pb2.Identifier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.UserService/GetUser',
            chirp__pb2.UserRequest.SerializeToString,
            chirp__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.UserService/UpdateUser',
            chirp__pb2.UpdateUserRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFollowing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.UserService/GetFollowing',
            chirp__pb2.GetUsersRequest.SerializeToString,
            chirp__pb2.Users.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFollowers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.UserService/GetFollowers',
            chirp__pb2.GetUsersRequest.SerializeToString,
            chirp__pb2.Users.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FollowUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.UserService/FollowUser',
            chirp__pb2.UserRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnfollowUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.UserService/UnfollowUser',
            chirp__pb2.UserRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/chirp.AuthService/CreateSession',
                request_serializer=chirp__pb2.Credentials.SerializeToString,
                response_deserializer=chirp__pb2.Session.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/chirp.AuthService/GetSession',
                request_serializer=chirp__pb2.SessionRequest.SerializeToString,
                response_deserializer=chirp__pb2.Session.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/chirp.AuthService/DeleteSession',
                request_serializer=chirp__pb2.SessionRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=chirp__pb2.Credentials.FromString,
                    response_serializer=chirp__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=chirp__pb2.SessionRequest.FromString,
                    response_serializer=chirp__pb2.Session.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=chirp__pb2.SessionRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chirp.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chirp.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.AuthService/CreateSession',
            chirp__pb2.Credentials.SerializeToString,
            chirp__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.AuthService/GetSession',
            chirp__pb2.SessionRequest.SerializeToString,
            chirp__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.AuthService/DeleteSession',
            chirp__pb2.SessionRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PostServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/chirp.PostService/CreatePost',
                request_serializer=chirp__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=chirp__pb2.Identifier.FromString,
                _registered_method=True)
        self.GetFeed = channel.unary_unary(
                '/chirp.PostService/GetFeed',
                request_serializer=chirp__pb2.GetFeedRequest.SerializeToString,
                response_deserializer=chirp__pb2.Posts.FromString,
                _registered_method=True)
        self.GetPosts = channel.unary_unary(
                '/chirp.PostService/GetPosts',
                request_serializer=chirp__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=chirp__pb2.Posts.FromString,
                _registered_method=True)
        self.GetLikedPosts = channel.unary_unary(
                '/chirp.PostService/GetLikedPosts',
                request_serializer=chirp__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=chirp__pb2.Posts.FromString,
                _registered_method=True)
        self.GetPost = channel.unary_unary(
                '/chirp.PostService/GetPost',
                request_serializer=chirp__pb2.PostRequest.SerializeToString,
                response_deserializer=chirp__pb2.Post.FromString,
                _registered_method=True)
        self.DeletePost = channel.unary_unary(
                '/chirp.PostService/DeletePost',
                request_serializer=chirp__pb2.PostRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)
        self.LikePost = channel.unary_unary(
                '/chirp.PostService/LikePost',
                request_serializer=chirp__pb2.PostRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)
        self.UnlikePost = channel.unary_unary(
                '/chirp.PostService/UnlikePost',
                request_serializer=chirp__pb2.PostRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)
        self.RepostPost = channel.unary_unary(
                '/chirp.PostService/RepostPost',
                request_serializer=chirp__pb2.PostRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveRepost = channel.unary_unary(
                '/chirp.PostService/RemoveRepost',
                request_serializer=chirp__pb2.PostRequest.SerializeToString,
                response_deserializer=chirp__pb2.Empty.FromString,
                _registered_method=True)


class PostServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLikedPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LikePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlikePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RepostPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRepost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=chirp__pb2.CreatePostRequest.FromString,
                    response_serializer=chirp__pb2.Identifier.SerializeToString,
            ),
            'GetFeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeed,
                    request_deserializer=chirp__pb2.GetFeedRequest.FromString,
                    response_serializer=chirp__pb2.Posts.SerializeToString,
            ),
            'GetPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosts,
                    request_deserializer=chirp__pb2.GetPostsRequest.FromString,
                    response_serializer=chirp__pb2.Posts.SerializeToString,
            ),
            'GetLikedPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLikedPosts,
                    request_deserializer=chirp__pb2.GetPostsRequest.FromString,
                    response_serializer=chirp__pb2.Posts.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=chirp__pb2.PostRequest.FromString,
                    response_serializer=chirp__pb2.Post.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=chirp__pb2.PostRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
            'LikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.LikePost,
                    request_deserializer=chirp__pb2.PostRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
            'UnlikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlikePost,
                    request_deserializer=chirp__pb2.PostRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
            'RepostPost': grpc.unary_unary_rpc_method_handler(
                    servicer.RepostPost,
                    request_deserializer=chirp__pb2.PostRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
            'RemoveRepost': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRepost,
                    request_deserializer=chirp__pb2.PostRequest.FromString,
                    response_serializer=chirp__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chirp.PostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chirp.PostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/CreatePost',
            chirp__pb2.CreatePostRequest.SerializeToString,
            chirp__pb2.Identifier.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/GetFeed',
            chirp__pb2.GetFeedRequest.SerializeToString,
            chirp__pb2.Posts.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/GetPosts',
            chirp__pb2.GetPostsRequest.SerializeToString,
            chirp__pb2.Posts.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLikedPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/GetLikedPosts',
            chirp__pb2.GetPostsRequest.SerializeToString,
            chirp__pb2.Posts.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/GetPost',
            chirp__pb2.PostRequest.SerializeToString,
            chirp__pb2.Post.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/DeletePost',
            chirp__pb2.PostRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/LikePost',
            chirp__pb2.PostRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/UnlikePost',
            chirp__pb2.PostRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RepostPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/RepostPost',
            chirp__pb2.PostRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveRepost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chirp.PostService/RemoveRepost',
            chirp__pb2.PostRequest.SerializeToString,
            chirp__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
